version: '2'

services:
  aliyun-proxy-api:
    image: aliyun-proxy-api:0.0.3
    container_name: aliyun-proxy-api
    ports:
      - 2376:3000
    volumes:
      - "./src/data/aliyun.json:/app/data/aliyun.json"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
